class ModelVariable {
  static var logindata;
  static var userDetail;
  static var carCompany;
  static var carType;
  static var feedback;
  static var contactus;
  static var banner;
  static var carmela;
  static var follow;
  static var location;
  static var carmelaFilter;
  static var carFilter;
  static var carFilterData;
  static var car;
  static var recent_view;
  static var wish_list;
  static var testDrive;
  static var specification;
  static var bankRate;
  static var aboutUs;
  static var privacyPolicy;
  static var termsCondition;
  static var faqs;
  static var carReview;
  static var carmelaReview;
}